apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageflow-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pageflow-api
  template:
    metadata:
      labels:
        app: pageflow-api
    spec:
      containers:
        - name: pageflow-api
          image: ghcr.io/ToriCrux/pageflow-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/pageflow
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"