apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageflow-front-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pageflow-front
  template:
    metadata:
      labels:
        app: pageflow-front
    spec:
      containers:
        - name: pageflow-front
          image: ghcr.io/ToriCrux/pageflow-front:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://pageflow-api-service:8080