name: Backend CI

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test
        run: mvn -B package
        working-directory: ./PageFlow-api

      - name: Gerar selo (badge) do JaCoCo
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: PageFlow-api/target/site/jacoco/jacoco.csv
          generate-branches-badge: true
          badges-directory: .github/badges

      - name: Fazer commit do selo (se houver mudança)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add .github/badges/jacoco.svg .github/badges/branches.svg
          
          git commit -m "Autogenerated JaCoCo coverage badge" || exit 0
          
          git push