name: Backend CI

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./PageFlow-api

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Clear Maven Cache
        run: rm -rf ~/.m2/repository

      - name: Install Dependencies
        run: mvn dependency:purge-local-repository clean install

      - name: Run Tests with Coverage
        run: mvn clean verify

      - name: Gerar selo (badge) do JaCoCo
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: PageFlow-api/target/site/jacoco/jacoco.csv
          generate-branches-badge: true
          badges-directory: PageFlow-api/.github/badges

      - name: Fazer commit do selo (se houver mudança)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add PageFlow-api/.github/badges/jacoco.svg PageFlow-api/.github/badges/branches.svg || echo "Badges not found, skipping add"
          git commit -m "Autogenerated JaCoCo coverage badge" || echo "Nothing to commit"
          git push || echo "Nothing to push"
