name: PageFlow CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-test-backend:
    name: "Build & Test Backend"
    uses: "./.github/workflows/backend-ci.yml"
    permissions:
      contents: write

  build-test-frontend:
    needs: build-test-backend
    name: "Build & Test Frontend"
    uses: "./.github/workflows/frontend-ci.yml"

  build-and-run-compose:
    name: Build Images and Run Compose
    needs: [build-test-backend, build-test-frontend]
    runs-on: ubuntu-latest
    environment: development
    env:
      SPRING_DATASOURCE_URL: ${{ vars.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ vars.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }}
      NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PGADMIN_DEFAULT_EMAIL: ${{ vars.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Build and start services with Docker Compose
        run: docker compose up --build -d
      - name: Executar testes Selenium no container da API
        run: |
          docker compose exec -T api mvn clean verify